### ISSUE TITLE
Does not work well with moddle 2.8.3

### ISSUE THREAD

**Issue by fvendrell** [kamat/moodle-auth_mcae#14]
I got the following error message:
get_context_instance() is deprecated, please use context_xxxx::instance() instead.
line 3717 of /lib/deprecatedlib.php: call to debugging()
line 19 of /auth/mcae/view.php: call to get_context_instance()

When trying to replace get_context_instance(CONTEXT_SYSTEM) by context_system::instance() as advice elsewhre, I got others error messages:

Debug info: Argument 2 passed to require_capability() must be an instance of context, null given, called in [dirroot]/auth/mcae/view.php on line 22 and defined
Error code: codingerror
Stack trace:
    line 393 of /lib/setuplib.php: coding_exception thrown
    line 783 of /lib/accesslib.php: call to default_error_handler()
    line 22 of /auth/mcae/view.php: call to require_capability()

I seem that this very very very useful plugin needs an update!

**Comment by danmarsden** [comment]
looks like this one can be closed - the code uses context_system::instance() now.

**Comment by fvendrell** [comment]
Thank you :-)
